### ISSUE TITLE
www.reddit.com  REJECT  quad9-dnscrypt ?

### ISSUE THREAD

**Issue by Hangaro0** [Quad9DNS/dnscrypt-settings#11]
hi team Quad9DNS.
pc.. win81 32b .. dnscrypt-proxy.exe 
it's ok  .. ?
[2024-10-22 11:41:21]	127.0.0.1	www.reddit.com	A	REJECT	41ms	quad9-dnscrypt-ip4-filter-alt

www.reddit.com  REJECT ?

**Comment by johnhtodd** [comment]
Quad9 is not filtering reddit (see https://www.quad9.net/result/?url=www.reddit.com ), so it is uncertain where that reject message is coming from.  See a similar ticket where the name was in a local file:

https://github.com/DNSCrypt/dnscrypt-proxy/discussions/2654

**Comment by Hangaro0** [comment]
Thanks for the quick response and clarification.

**Comment by Hangaro0** [comment]
I blocked ".fastly.net" and consequently "www.reddit.com" did not work.. it was my mistake, sorry for the inconvenience.

c,md:  dnscrypt-proxy -resolve "www.reddit.com"

`dnscrypt-proxy -resolve "www.reddit.com"
Resolving [www.reddit.com] using 127.10.10.11 port 53

Resolver      : 200.25.81.149

Canonical name: reddit.map.fastly.net.

IPv4 addresses: -
IPv6 addresses: -

Name servers  : no name servers found
DNSSEC signed : no
Mail servers  : no mail servers found

HTTPS alias   : -
HTTPS info    : -

Host info     : This query has been locally blocked by dnscrypt-proxy
TXT records   : -`
